In [2]:
import tensorflow as tf
a = tf.constant(1.0)
b = tf.constant(2.0)
c = tf.add(a,b)
print(a,b,c)


Tensor("Const_2:0", shape=(), dtype=float32) Tensor("Const_3:0", shape=(), dtype=float32) Tensor("Add_1:0", shape=(), dtype=float32)


In [3]:
d = tf.constant(1.0,name='d')
e = tf.constant(2.0,name='e')
f = tf.add(d,e)
with tf.Session() as sess:
    print(f.eval())
    print(sess.run([d,e,f]))

3.0
[1.0, 2.0, 3.0]


In [8]:
a =tf.constant([[1,2,3],[4,5,6]],name='a')
b = tf.constant([[7,8,9],[10,11,12]],name='b')
c = tf.add(a,b)
f = a.consumers()
with tf.Session() as sess:
    print(a.get_shape())
    print(sess.run(f))
    print(a.eval())
   

(2, 3)
[None]
[[1 2 3]
 [4 5 6]]


In [9]:
a = tf.constant([[-1, -2, -3], [4, 5, 6]], name = 'a')
b = tf.constant([[7, 8, 9], [10, 11, 12]], name = 'b')
c = tf.constant([[7, 8], [9, 10], [11, 12]], name = 'c')

d = tf.add(a, b)
# 对应元素相减
f = tf.subtract(a, b)
# 对应元素相乘
e = tf.multiply(a, b)
# 矩阵相乘
g = tf.matmul(b, c)
with tf.Session() as sess:
    print(sess.run(d))
    print(sess.run(e))
    print(sess.run(f))
    print(sess.run(g))
    # 获取绝对值
    print(sess.run(tf.abs(a)))
    # 数据取相反数
    print(sess.run(tf.negative(a)))
    # 取出张量值
    print(a.eval())

[[ 6  6  6]
 [14 16 18]]
[[ -7 -16 -27]
 [ 40  55  72]]
[[ -8 -10 -12]
 [ -6  -6  -6]]
[[220 244]
 [301 334]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [-4 -5 -6]]
[[-1 -2 -3]
 [ 4  5  6]]


In [10]:
sp = tf.SparseTensor(indices = [[0, 2], [1, 3]], values = [1, 2], dense_shape = [3, 4])
with tf.Session() as sess:
    print(sp.eval())

SparseTensorValue(indices=array([[0, 2],
       [1, 3]]), values=array([1, 2], dtype=int32), dense_shape=array([3, 4]))
