In [1]:
import numpy as np


In [2]:
list = [1,2,3,4]
a = np.array(list)

In [5]:
a.dtype

dtype('int64')

In [4]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.size

4

In [14]:
a = np.zeros((3,4,5))

In [15]:
a.shape


(3, 4, 5)

In [16]:
b = np.arange(1,11,3)

In [17]:
b

array([ 1,  4,  7, 10])

In [20]:
c = b.reshape((2,2))

In [21]:
 c

array([[ 1,  4],
       [ 7, 10]])

In [28]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [29]:
a = np.arange(0,20)

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
a = a.reshape([4,5])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
np.apply_along_axis(func1d=np.max, arr=a, axis=0)

array([15, 16, 17, 18, 19])

In [38]:
def my_fun(a):
    return np.max(a)-np.min(a)

In [40]:
np.apply_along_axis(func1d=my_fun, arr=a, axis=1)

array([4, 4, 4, 4])

In [45]:
a = np.random.random((5,5))

In [46]:
a

array([[0.28613743, 0.41204211, 0.30222183, 0.39666886, 0.86258223],
       [0.72669768, 0.94431385, 0.0305284 , 0.18535454, 0.05562792],
       [0.38489598, 0.02189984, 0.74280973, 0.86667524, 0.0478392 ],
       [0.03881924, 0.46222779, 0.40807775, 0.44465696, 0.93962533],
       [0.35599411, 0.14858695, 0.03443983, 0.12277389, 0.48125512]])

In [51]:
a= np.array([[1,2,3],[7,8,9]])
b = np.array([[5,6,7],[0,0,0]])


In [52]:
c = np.row_stack((a,b))

array([[1, 2, 3],
       [7, 8, 9],
       [5, 6, 7],
       [0, 0, 0]])

In [53]:
np.column_stack((a,b))

array([[1, 2, 3, 5, 6, 7],
       [7, 8, 9, 0, 0, 0]])

In [54]:
a = np.arange(20).reshape([4,5])


In [55]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [60]:
np.vsplit(a,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [75]:
[a1,a2,a3,a4] = np.split(a,[0,3,4],axis=0)

In [76]:
a1

array([], shape=(0, 5), dtype=int64)

In [77]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
a3

array([[ 3],
       [ 8],
       [13],
       [18]])

In [74]:
a4

array([[ 4],
       [ 9],
       [14],
       [19]])

In [78]:
a = np.arange(16).reshape([4,4])

In [79]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
b = np.array([1,2,3,4])

In [83]:
a + b

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19]])